### ISSUE TITLE
关于支付功能

### ISSUE THREAD

**Issue by qiuxiaojian** [TencentCloudBase/mp-book#1]

**Comment by qiuxiaojian** [comment]
![image](https://user-images.githubusercontent.com/34261007/50548879-0ed1d500-0c8f-11e9-9b5a-207d50f5269f.png)
如果是调用本案例，请问除了商户API秘钥有误外，会出现签名有误的可能性有哪些的，我想了解一下

**Comment by qiuxiaojian** [comment]
已解决

**Comment by ACChe** [comment]
@qiuxiaojian 我和你一样的错误，应该怎么去解决？
