### ISSUE TITLE
unable to verify signature

### ISSUE THREAD

**Issue by ACChe** [TencentCloudBase/mp-book#4]
在获取到订单后，进行支付，报错： unable to verify signature。

**Comment by lcxfs1991** [comment]
有没有更详细的截图，是不是填错了配置了。

**Comment by ACChe** [comment]
配置没问题吧，使用 https://github.com/sigoden/wechatpay/tree/master 正常支付。
我看贵司代码里没有填appid，不过加上去也是不能支付。

**Comment by lcxfs1991** [comment]
这个报错信息：unable to verify signature

应该就是配置错了。

你截图一下你的配置（传的时候把敏感信息隐去吧）？

**Comment by ACChe** [comment]
![image](https://user-images.githubusercontent.com/1592763/51153358-cf200580-18aa-11e9-985c-4d0372334a01.png)

**Comment by lcxfs1991** [comment]
@ACChe 估计是证书没配置，我优化了一波，可以试试
