### ISSUE TITLE
杨晓州简历

### ISSUE THREAD

**Issue by FrankYangxz** [TencentCloudBase/mp-book#7]
[杨晓州-前端FE.pdf](https://github.com/TencentCloudBase/mp-book/files/2896946/-.FE.pdf)

**Comment by lcxfs1991** [comment]
已推

**Comment by FrankYangxz** [comment]
谢谢




| |
FrankYang
|
|
邮箱：yangxz5488@163.com
|

Signature is customized by Netease Mail Master

在2019年02月23日 23:44，heyli 写道：

已推
